name: TSec
baseurl: /tsec
description: A Type-Safe General Cryptography Library on the JVM
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.0.2+4-bc66ced2-SNAPSHOT
org: io.github.jmcardon
markdown: kramdown
