name: TSec
baseurl: /tsec
description: A Type-Safe General Cryptography Library on the JVM
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.1-ct-2+3-a3f403ed-SNAPSHOT
org: io.github.jmcardon
markdown: kramdown
